import 'package:flutter_test/flutter_test.dart';
import 'package:pka_home/data/models/issue_rating_model.dart';

void main() {
  group('IssueRatingModel TDD Tests', () {
    final sampleJson = {
      'id': 'rating-uuid-123',
      'issue_report_id': 'issue-uuid-456',
      'reporter_id': 'user-uuid-789',
      'speed_rating': 5,
      'attitude_rating': 4,
      'quality_rating': 5,
      'overall_rating': 4.7,
      'comment': 'Kỹ thuật viên xử lý rất nhanh và tận tâm!',
      'created_at': '2026-09-29T10:00:00Z',
      'updated_at': '2026-09-29T10:05:00Z',
      'users': {
        'full_name': 'Nguyễn Văn Cư Dân',
      },
      'apartments': {
        'code': 'A0110',
      },
    };

    test('fromJson parses all fields correctly including nested user and apartment', () {
      final model = IssueRatingModel.fromJson(sampleJson);

      expect(model.id, 'rating-uuid-123');
      expect(model.issueReportId, 'issue-uuid-456');
      expect(model.reporterId, 'user-uuid-789');
      expect(model.speedRating, 5);
      expect(model.attitudeRating, 4);
      expect(model.qualityRating, 5);
      expect(model.overallRating, 4.7);
      expect(model.comment, 'Kỹ thuật viên xử lý rất nhanh và tận tâm!');
      expect(model.createdAt, DateTime.parse('2026-09-29T10:00:00Z'));
      expect(model.updatedAt, DateTime.parse('2026-09-29T10:05:00Z'));
      expect(model.reporterName, 'Nguyễn Văn Cư Dân');
      expect(model.apartmentCode, 'A0110');
    });

    test('toJson serializes core fields correctly for database insertion/update', () {
      final model = IssueRatingModel(
        id: 'rating-uuid-123',
        issueReportId: 'issue-uuid-456',
        reporterId: 'user-uuid-789',
        speedRating: 5,
        attitudeRating: 4,
        qualityRating: 5,
        overallRating: 4.7,
        comment: 'Tuyệt vời',
        createdAt: DateTime.parse('2026-09-29T10:00:00Z'),
      );

      final json = model.toJson();

      expect(json['issue_report_id'], 'issue-uuid-456');
      expect(json['reporter_id'], 'user-uuid-789');
      expect(json['speed_rating'], 5);
      expect(json['attitude_rating'], 4);
      expect(json['quality_rating'], 5);
      expect(json['comment'], 'Tuyệt vời');
      // overall_rating is generated by DB so not included in insert/update payload
      expect(json.containsKey('overall_rating'), isFalse);
    });

    test('calculates computed overall rating if DB overall_rating is null', () {
      final jsonWithoutOverall = {
        'id': 'rating-uuid-123',
        'issue_report_id': 'issue-uuid-456',
        'reporter_id': 'user-uuid-789',
        'speed_rating': 4,
        'attitude_rating': 4,
        'quality_rating': 4,
        'overall_rating': null,
        'created_at': '2026-09-29T10:00:00Z',
      };

      final model = IssueRatingModel.fromJson(jsonWithoutOverall);
      expect(model.overallRating, 4.0);
    });

    test('satisfactionLabel returns accurate Vietnamese description based on overall rating', () {
      expect(IssueRatingModel.getSatisfactionLabel(5.0), 'Rất hài lòng');
      expect(IssueRatingModel.getSatisfactionLabel(4.5), 'Rất hài lòng');
      expect(IssueRatingModel.getSatisfactionLabel(4.0), 'Hài lòng');
      expect(IssueRatingModel.getSatisfactionLabel(3.0), 'Bình thường');
      expect(IssueRatingModel.getSatisfactionLabel(2.0), 'Chưa hài lòng');
      expect(IssueRatingModel.getSatisfactionLabel(1.0), 'Rất thất vọng');
    });

    test('copyWith updates specified fields correctly', () {
      final model = IssueRatingModel.fromJson(sampleJson);
      final updated = model.copyWith(
        comment: 'Đã cập nhật nhận xét',
        attitudeRating: 5,
      );

      expect(updated.comment, 'Đã cập nhật nhận xét');
      expect(updated.attitudeRating, 5);
      expect(updated.speedRating, 5);
      expect(updated.id, model.id);
    });
  });
}
